use clap::Parser;

/// Manage UKI files generated by booster and systemd-ukify.
#[derive(Parser, Debug)]
pub struct Args {
    /// Generate UKI file for specified kernel package name
    #[arg(short, value_name = "package")]
    generate: Option<String>,

    /// Generate UKI files for all installed kernels
    #[arg(short = 'G')]
    generate_all: bool,

    /// Remove UKI file for specified kernel package name
    #[arg(short, value_name = "package")]
    remove: Option<String>,

    /// Remove initramfs*, booster*, vmlinuz* files, entire esp/EFI/Linux dir and other leftovers
    #[arg(short = 'C')]
    clean: bool,

    /// Remove known booster*, vmlinuz*, UKI files and other leftovers for all installed kernels
    #[arg(short = 'R')]
    remove_all: bool,
}

pub mod parser;
